server:
  http_listen_port: 8080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: app
    static_configs:
      - targets:
          - localhost
        labels:
          job: app-logs
          __path__: /var/lib/docker/containers/715144dacf9e560c2ecc842f977f383027f481a423de33d1e3ea35b6722d0003/*.log
    pipeline_stages:
      - json:
          expressions:
            log:
            stream:
            time:
      - json:
          source: log
          expressions:
            time:
            level:
            msg:
      - labels:
          level:
      - output:
          source: msg