server:
  http_listen_port: 8080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: app-logs
          __path__: /var/lib/docker/containers/*/*.log
    pipeline_stages:
      - docker: { }
      - json:
          expressions:
            time:
            level:
            msg:
            app_name:
      - labels:
          level:
          app_name:
      - output:
          source: msg